### ISSUE TITLE
Keybard not showing on iPhone 8

### ISSUE THREAD

**Issue by nriccar** [flyerhq/react-native-keyboard-accessory-view#1]
<img width="1440" alt="Screenshot 2020-06-13 at 16 46 10" src="https://user-images.githubusercontent.com/49196314/84571721-6554a580-ad95-11ea-8cf9-69ff1aa2b00f.png">

Is this library only for iPhone X+?

**Comment by demchenkoalex** [comment]
Hi! No, the library should support every iPhone as well as Android, iPhone X is featured on a gif, just because it was the hardest to support :)

Just ran the example on the iPhone SE simulator to double check - I can see the accessory view.

Can you please share the code you wrote, so we can investigate further? Thank you.

**Comment by demchenkoalex** [comment]
Closing due to no response, feel free to open again if problem is not resolved.
