### ISSUE TITLE
Why not use the Animated API?

### ISSUE THREAD

**Issue by SudoPlz** [flyerhq/react-native-keyboard-accessory-view#2]
Hey there,

I noticed that in order to move that view around, you just change the [bottom property](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/styles.ts#L19) on [a View](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/master/src/KeyboardAccessoryView.tsx#L54).

This all takes place on the JS thread, so I'm wondering, is there any reason you're not using the Animated api and make sure all of that runs on the main thread?

Doesn't that make your library slower and less performant?

Thanks

**Comment by demchenkoalex** [comment]
Hi, thanks for the comment. I am using `LayoutAnimation` to animate the transition, and that chunk of code is taken from the [React Native](https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/KeyboardAvoidingView.js#L107). During the interactive dismiss I have the Y position so it was straightforward to me to just place it as a bottom for the view, so I have never really considered Animated API.

Regarding the performance, some optimisations were added (like `useCallback`) and I did verify performance penalty using Profiler in Flipper, and saw mostly green updates.

How would you see Animated API implemented here? I will just drive it's value using PanResponder and apply it to the translate transformation or something?

Thanks

**Comment by SudoPlz** [comment]
Interesting, I'm not aware of `LayoutAnimation` but it looks it's just gradually changing the `keyboardEndPositionY` value.

That being said, since that's a value that get's changed on the JS side I think there would be a performance benefit from making that property an `Animated.Value` and turning this code:

`<View style={StyleSheet.flatten([container, style])} testID='container'>`

to something like:

`<Animated.View style={StyleSheet.flatten([container, style])} testID='container'>`

and the container style object:

```
container: {
      position: 'absolute',
      transform: [{
            translateY: newKeyboardValue,
      }],
      left: 0,
      right: 0,
    },
```

`newKeyboardValue` should be an `Animated.Value` object created from the equivalent Animated method code ([example](https://reactnative.dev/docs/animated#subtract)) resulting from [this](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/85fcd1567015eb2f1650bdfe673de2a08a4e2868/src/KeyboardAccessoryView.tsx#L30:L31).

I have a very hard time with hooks, so I don't feel confident making those changes myself. :/

Thanks for your quick response and the work you've put into this library.

**Comment by demchenkoalex** [comment]
Thanks for the suggestions and I will look into it, hopefully making this even faster :)

**Comment by demchenkoalex** [comment]
Hi @SudoPlz!

I have spent some time yesterday and come up with something, you can see the changes [here](https://github.com/flyerhq/react-native-keyboard-accessory-view/commit/e91c14bc498808e17e233277b817003df189643e).  (`feature/animated` branch)

Basically, main differences are:
- `usePanResponder` which returns an Animated value
```typescript
const panResponder = React.useRef(
  PanResponder.create({
    onPanResponderMove: Animated.event([null, { moveY: positionY }], {
      useNativeDriver: false,
    }),
    onPanResponderEnd: () =>
      Animated.timing(positionY, {
        duration: 0,
        toValue: 0,
        useNativeDriver: false,
      }).start(),
  })
).current
```
- some calculations in the `KeyboardAccessoryView`
```typescript
const deltaY = Animated.subtract(
  panResponderPositionY ?? new Animated.Value(0),
  keyboardEndPositionY
)
...
<Animated.View
  style={StyleSheet.flatten([
    {
      bottom: keyboardHeight,
      transform: [
        {
          translateY: deltaY.interpolate({
            inputRange: [0, Number.MAX_VALUE],
            outputRange: [0, Number.MAX_VALUE],
            extrapolate: 'clamp',
          }),
        },
      ],
    },
    container,
    style,
  ])}
  testID='container'
>
```
As you can see, I left a `bottom` property with a `keyboardHeight` value, so we only animate the pan gesture, no need to make `useKeyboardDimensions` to return Animated, because it works perfectly and on Android there is no animation whatsoever + `contentBottomInset` is calculated based on the keyboard and accessory view sizes and it is better to be a number, not Animated.

This solution works, but there is one problem I can't solve which looks like this

![demo](https://user-images.githubusercontent.com/14123304/84755094-87327000-afc1-11ea-957a-deccba336173.gif)

This is because this piece of code makes an animation when keyboard hides, starting from the previous state, `bottom` position, which is changed between 0 and `keyboardHeight`
```typescript
if (duration && easing) {
  // We have to pass the duration equal to minimal accepted duration defined here: RCTLayoutAnimation.m
  const animationDuration = Math.max(duration, 10)

  LayoutAnimation.configureNext({
    duration: animationDuration,
    update: {
      duration: animationDuration,
      type: LayoutAnimation.Types[easing],
    },
  })
}
```
and previously, in the `onPanResponderEnd` function, simple delay was enough `setTimeout(() => setPositionY(0), 10)`, but it is not the case with the Animated value.

I'd rather have less performant version, but without artefacts, what do you think? I will also try change some things here and there, but I am not sure I will able to resolve this problem.

UPD: No luck. Tried `Animated.setValue`, with and without `setTimeout`, `Animated.timing` with and without delay, duration, `LayoutAnimation`, everything is the same or worse 😕

**Comment by demchenkoalex** [comment]
https://github.com/flyerhq/react-native-keyboard-accessory-view/pull/3 Resolved by driving `bottom` value, not `translateY`. Saw a performance boost. Thanks @SudoPlz once again 👍

**Comment by SudoPlz** [comment]
Wow, greaaaat work @demchenkoalex kudos my friend!!

**Comment by SudoPlz** [comment]
That being said, why did you turn `useNativeDriver` to [false](https://github.com/flyerhq/react-native-keyboard-accessory-view/blob/1ef44e6fc6e5fc98e96f9d682d8dea61c34e3643/src/hooks/usePanResponder.tsx#L24)?
Can you enable that to make sure those animations run on the main thread?
When it's set to false, they still run on the js thread.

**Comment by demchenkoalex** [comment]
@SudoPlz it is crashing with `true` ;) says something about `PanResponder` not working with `useNativeDriver`
