### ISSUE TITLE
When I input return, textinput is not follow my cursor

### ISSUE THREAD

**Issue by alantoa** [flyerhq/react-native-keyboard-accessory-view#26]
When I input return, textinput's cursor is not follow my input

**Comment by demchenkoalex** [comment]
Hi @MonsterAnan this library only renders a view above the keyboard, everything else is on your side. What makes you think the problem is in the library and what can I do?

**Comment by alantoa** [comment]
Hi, thanks for you reply!  @demchenkoalex 

### This is my problem video url :
[Video](https://upload.42how.com/article/202108120639-bug.mp4)

#### Desc:
I press *enter* key,
When I use English keyboard,  it's ok,
When I use Other( such as Chinese Keyboard ) keyboard, I prsee *enter* key, cursor  it's  not follow my input.

I guess it's onLayout bug?

**Comment by demchenkoalex** [comment]
Thanks. I watched a video, looks like a very specific use case when you have a scrollable which contains multi line text input and when you create a new line it doesn't automatically scroll but it does scroll after some delay?

**Comment by alantoa** [comment]
It doesn't delay scroll, that is my finger trigger 👆 . The video just to demonstrate.
Only If I type in some words , It scroll. 
This makes me very curious. 🙁

**Comment by demchenkoalex** [comment]
So I have tried having `TextInput` inside the `ScrollView` and I think it's something I will not be able to handle, since multiline `TextInput` scrolls itself, and when added inside the `ScrollView` it's just a 🎪, everything starts jumping around, I can't normally dismiss the keyboard etc etc. If I will put `TextInput` inside `renderScrollable` directly, without any scrollable, it will work, but then keyboard is not dismissible at all. So I guess either UX will need to change (e.g. no scrollable and some button to hide the keyboard or accept the input) or some simple `KeyboardAvoidingView` will be better in this case.

**Comment by alantoa** [comment]
Thank you very much, This is a  very good project on the keyboard.😊
I'll try to solve the problems

**Comment by demchenkoalex** [comment]
Thanks!
