### ISSUE TITLE
Tab Bar issue

### ISSUE THREAD

**Issue by mortocks** [flyerhq/react-native-keyboard-accessory-view#4]
Not sure if this is my implementation or the library but having trouble with layouts using the library with a react-navigation tab bar.

When the keyboard is show, the KeyboardAccessoryView has a space between the keyboard and the bottom of the view equal to the height of the toolbar. 

![Screen Recording 2020-08-10 at 1 56 42 pm](https://user-images.githubusercontent.com/314196/89750984-a6590400-db11-11ea-84a3-823595d6cf6d.gif)

**Comment by demchenkoalex** [comment]
Hello,

Thank you for the question.

It is the problem in the library most definitely. I didn't think about tab bar case because it is not common to have a chat screen with a visible tab bar (usually when you have a chat in a tab there is a list of people you are currently chatting with, and when you select one - you present a chat screen without a tab bar visible). Also, tab bar takes some space, so you see less messages.

Because of above I wouldn't do automatic detection of a tab bar, but I can try adding a prop where you can specify a custom offset - you would need to know the height of a tab bar.

What do you think?

**Comment by mortocks** [comment]
I think a custom offset prop would be the way to go - that way the library could support different scenarios rather than just adding "Tab bar" support.

**Comment by demchenkoalex** [comment]
Hi @mortocks, hopefully fixed in https://github.com/flyerhq/react-native-keyboard-accessory-view/pull/5, I have also added a new section to the README regarding this, please read [it](https://github.com/flyerhq/react-native-keyboard-accessory-view#handling-wrong-offsets). Let me know if that works for you. Thanks!

**Comment by mortocks** [comment]
Nice - confirmed on iOS that this additional api allows support of a tab bar. Not to future devs that you're going to want to take bottom insets into account rather than just hard coding a variable but the api works as you'd expect. 

Thanks

**Comment by demchenkoalex** [comment]
Thanks! Yes, you are correct, you should use bottom safe area insets and/or the size of a component that is adding unwanted margins, I've described the whole process in the docs - https://github.com/flyerhq/react-native-keyboard-accessory-view#handling-wrong-offsets
