### ISSUE TITLE
Doesn't work on android

### ISSUE THREAD

**Issue by tankers746** [flyerhq/react-native-keyboard-accessory-view#8]
It appears that the event 'keyboardWillChangeFrame' is not fired on android.

**Comment by demchenkoalex** [comment]
Hi @tankers746 what do you mean by not working? The accessory view doesn't appear above the keyboard? According to the React Native docs https://reactnative.dev/docs/keyboard
```
Note that if you set android:windowSoftInputMode to adjustResize or adjustPan, only keyboardDidShow and keyboardDidHide events will be available on Android. If you set android:windowSoftInputMode to adjustNothing, no events will be available on Android.
```
In the example I have `adjustResize` and it works, what do you have? I guess there might be problems supporting `adjustPan` or `adjustNothing`, especially latter.

**Comment by tankers746** [comment]
Yeah I have android:windowSoftInputMode set to `adjustResize` and the event is not firing. As the docs describe, only 
 keyboardDidShow and keyboardDidHide fire. The result is that the accessory view doesn't move from the bottom of the screen as `keyboardHeight` is never set.

**Comment by demchenkoalex** [comment]
Can you run the example project please and see if the accessory view is working for you on the same device you test your solution? The event is not fired indeed, just double checked, however the accessory view still remains on the top of the keyboard, I believe I left it that way because `adjustResize` should minimize the visible area and since the accessory view is absolutely attached to the visible bottom, it was working. I use Android Emulator with Android 11 and I believe it was working on my Xiaomi A1. Maybe it has to do with a particular manufacturer?

**Comment by tankers746** [comment]
After much struggle I was not able to get the example to run on my machine

```Error: Unable to resolve module @babel/runtime/helpers/slicedToArray from ../lib/hooks/useComponentSize.js: @babel/runtime/helpers/slicedToArray could not be found within the project.```

I was however looking at LayoutAnimation and it looks like its not enabled by default on Android anyways.
Would you be open to a PR using reanimated V2? Should be much better performance on Android.

**Comment by demchenkoalex** [comment]
Thank you for your time @tankers746 sorry to hear that you wasn't able to run the example and the error looks strange to me, can't recommend a solution. I thought that `yarn` in both root and example folder and `yarn android` should be enough to run the example, but apparently there might be some problems on different machines.

I looked through the code once more and I have realized that basically everything you see in the `useKeyboardDimensions` is used for the interactive dismiss on iOS and Android basically just uses `adjustResize`. That means `LayoutAnimation` is used on iOS only. Basically Android should never call that code and it shouldn't affect its performance. Actually, since Android doesn't have an interactive keyboard dismiss, I can see that there might be a specific solution which uses `keyboardDidShow` and `keyboardDidHide` events just to set the height of the keyboard so the accessory view possibly renders correctly in your case and in case of `adjustPan` is used. I might try to do this when I have more time.

Reanimated V2 will improve performance on iOS, and I planned to do it myself, however I am waiting for the actual release and when `react-navigation` will adopt V2 so most people won't need this big dependency for this small library, since they will already have it from `react-navigation`. I believe `react-native-gesture-handler` might also be needed, but right now I don't plan to add those huge dependencies just to improve the performance a bit on one platform.

**Comment by tankers746** [comment]
Ah my mistake, a yarn install in the root directory fixed it.
And it does work on the demo app, something strange is going on I will look into whats different about my specific app.

**Comment by demchenkoalex** [comment]
Thanks for pointing out that yarn is needed in the root folder, will add it to the docs

**Comment by tankers746** [comment]
The issue was due to some code to hide the status bar in my MainActivity.java
```getWindow().getDecorView().setSystemUiVisibility(
            View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
    }
```
This seems to disable the window resizing of `adjustResize`

**Comment by demchenkoalex** [comment]
Thanks for letting me know @tankers746 🙂 I will see what I can do about it.

**Comment by tankers746** [comment]
I've created a PR https://github.com/flyerhq/react-native-keyboard-accessory-view/pull/9

I've tested on my app and the example and works well.
I did have to change from using the `Dimensions` module to using the `useSafeAreaFrame` from `react-native-safe-area-context` as the window height wasn't taking into account the app-switching bar on Android 10.

**Comment by tankers746** [comment]
Also, on my thought about moving to Reanimated. It seems that the easing mode 'keyboard' is only provided by the LayoutAnimation module. The lovely slide-in-time with the keyboard you get on iOS with LayoutAnimation doesn't seem possible with any other animation library.

**Comment by demchenkoalex** [comment]
Thanks @tankers746 I will merge it to some other branch since I need to fix styles, linter, possibly tests and I can't do that on a PR itself. Then I will merge this branch to the main.

**Comment by demchenkoalex** [comment]
@tankers746 I have added a new prop `useListenersOnAndroid` (boolean), because your fix was breaking an example with `adjustResize`. By default the library will not use any listeners, but in your case you will need to pass this prop and hopefully everything will work 🙂 New version 1.6.0 is available on NPM. Let me know if this works.

**Comment by tankers746** [comment]
Tested and works great, thanks for the quick resolution!
